{"name": "Attempted login with valid and invalid credentials -- @1.3 ", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\Zahri Hidayat\\.conda\\envs\\Softwar_Testing\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Zahri Hidayat\\.conda\\envs\\Softwar_Testing\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Login_steps.py\", line 32, in step_impl\n    assert error_message.text == message\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1716117598543, "stop": 1716117598595}, {"name": "When I fill in \"username\" with \"\"", "status": "passed", "start": 1716117598595, "stop": 1716117598596}, {"name": "And I fill in \"Password\" with \"\"", "status": "passed", "start": 1716117598596, "stop": 1716117598596}, {"name": "And I press \"Login\"", "status": "passed", "start": 1716117598596, "stop": 1716117598640}, {"name": "Then I should see \"negative\" with this \"Epic sadface: Username and password are required\"", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\Zahri Hidayat\\.conda\\envs\\Softwar_Testing\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Zahri Hidayat\\.conda\\envs\\Softwar_Testing\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Login_steps.py\", line 32, in step_impl\n    assert error_message.text == message\n"}, "start": 1716117598640, "stop": 1716117598655}], "parameters": [{"name": "username"}, {"name": "password"}, {"name": "message_type", "value": "negative"}, {"name": "message", "value": "Epic sadface: Username and password are required"}], "start": 1716117598542, "stop": 1716117598656, "uuid": "ee61d101-8eb8-4438-9225-5b23dcc299f4", "historyId": "bdb0055ea5226e5ed882f27d773c99e7", "fullName": "Login: Attempted login with valid and invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}