{"name": "Attempted login with valid and invalid credentials -- @1.3 ", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\Zahri Hidayat\\.conda\\envs\\Softwar_Testing\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Zahri Hidayat\\.conda\\envs\\Softwar_Testing\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Login_steps.py\", line 32, in step_impl\n    assert error_message.text == message\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1716114862166, "stop": 1716114862246}, {"name": "When I fill in \"username\" with \"\"", "status": "passed", "start": 1716114862246, "stop": 1716114862247}, {"name": "And I fill in \"Password\" with \"\"", "status": "passed", "start": 1716114862248, "stop": 1716114862248}, {"name": "And I press \"Login\"", "status": "passed", "start": 1716114862248, "stop": 1716114862309}, {"name": "Then I should see \"negative\" with this \"Epic sadface: Username and password are required\"", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\Zahri Hidayat\\.conda\\envs\\Softwar_Testing\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Zahri Hidayat\\.conda\\envs\\Softwar_Testing\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Login_steps.py\", line 32, in step_impl\n    assert error_message.text == message\n"}, "start": 1716114862309, "stop": 1716114862329}], "parameters": [{"name": "username"}, {"name": "password"}, {"name": "message_type", "value": "negative"}, {"name": "message", "value": "Epic sadface: Username and password are required"}], "start": 1716114862165, "stop": 1716114862330, "uuid": "4ec04556-bead-418a-9b31-06a0de3d6028", "historyId": "bdb0055ea5226e5ed882f27d773c99e7", "fullName": "Login: Attempted login with valid and invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}