{"name": "Attempted login with valid and invalid credentials -- @1.2 ", "status": "passed", "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1716117598140, "stop": 1716117598209}, {"name": "When I fill in \"username\" with \"standard\"", "status": "passed", "start": 1716117598209, "stop": 1716117598309}, {"name": "And I fill in \"Password\" with \"bond123\"", "status": "passed", "start": 1716117598309, "stop": 1716117598451}, {"name": "And I press \"Login\"", "status": "passed", "start": 1716117598452, "stop": 1716117598509}, {"name": "Then I should see \"negative\" with this \"Epic sadface: Username and password do not match any user in this service\"", "status": "passed", "start": 1716117598509, "stop": 1716117598541}], "parameters": [{"name": "username", "value": "standard"}, {"name": "password", "value": "bond123"}, {"name": "message_type", "value": "negative"}, {"name": "message", "value": "Epic sadface: Username and password do not match any user in this service"}], "start": 1716117598139, "stop": 1716117598541, "uuid": "b7dc5ce8-0f78-4a35-809c-0417cba4f5ac", "historyId": "9afba8b497ceeaa7ee0e03c9b0e38b7b", "fullName": "Login: Attempted login with valid and invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}