{"name": "Attempted login with valid and invalid credentials -- @1.2 ", "status": "passed", "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1716114861740, "stop": 1716114861846}, {"name": "When I fill in \"username\" with \"standard\"", "status": "passed", "start": 1716114861846, "stop": 1716114861960}, {"name": "And I fill in \"Password\" with \"bond123\"", "status": "passed", "start": 1716114861960, "stop": 1716114862070}, {"name": "And I press \"Login\"", "status": "passed", "start": 1716114862071, "stop": 1716114862141}, {"name": "Then I should see \"negative\" with this \"Epic sadface: Username and password do not match any user in this service\"", "status": "passed", "start": 1716114862141, "stop": 1716114862164}], "parameters": [{"name": "username", "value": "standard"}, {"name": "password", "value": "bond123"}, {"name": "message_type", "value": "negative"}, {"name": "message", "value": "Epic sadface: Username and password do not match any user in this service"}], "start": 1716114861738, "stop": 1716114862164, "uuid": "aec211d9-716e-4b22-9966-d4c721aec3be", "historyId": "9afba8b497ceeaa7ee0e03c9b0e38b7b", "fullName": "Login: Attempted login with valid and invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}