{"name": "Attempted login with valid and invalid credentials -- @1.6 ", "status": "passed", "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1716114863085, "stop": 1716114863134}, {"name": "When I fill in \"username\" with \"standard_bond\"", "status": "passed", "start": 1716114863135, "stop": 1716114863276}, {"name": "And I fill in \"Password\" with \"secret_sauce\"", "status": "passed", "start": 1716114863276, "stop": 1716114863400}, {"name": "And I press \"Login\"", "status": "passed", "start": 1716114863401, "stop": 1716114863448}, {"name": "Then I should see \"negative\" with this \"Epic sadface: Username and password do not match any user in this service\"", "status": "passed", "start": 1716114863448, "stop": 1716114863465}], "parameters": [{"name": "username", "value": "standard_bond"}, {"name": "password", "value": "secret_sauce"}, {"name": "message_type", "value": "negative"}, {"name": "message", "value": "Epic sadface: Username and password do not match any user in this service"}], "start": 1716114863084, "stop": 1716114863465, "uuid": "7b7ec0dd-2038-4e56-9d79-8fe513971659", "historyId": "44e6924ca4f4cb35666ca0aa307b4c45", "fullName": "Login: Attempted login with valid and invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}